### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by parliament718** [toniov/p-iteration#5]
The following error gets thrown from simply loading the library (not even calling it). 

Why does this happen? Am using node 8.1.0

```import { forEach } from 'p-iteration';```

OR

```const { forEach } = require('p-iteration');```

throws same error:

```
exports.forEach = async (array, callback, thisArg) => {
                        ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by bbeckrest** [comment]
@parliament718 did you ever solve this issue?

**Comment by toniov** [comment]
This error should only happen when you use a Node.js version not compatible with async functions (less than 8.0.0).

Could you check your Node version?
